name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Go fmt
        run: |
          files=$(gofmt -l ./cmd ./internal)
          if [ -n "$files" ]; then
            echo "These files need gofmt:\n$files"
            exit 1
          fi
      - name: Go vet
        run: go vet ./...
      - name: Run tests
        run: go test ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.59
          args: --timeout=5m
