name: Container

on:
  push:
    branches: [ main ]
  release:
    types: [published]

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/aionfs-devd

jobs:
  build-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build image
        run: docker build -t aionfs-devd:ci .
      - name: Smoke test
        run: |
          docker run --rm -d -p 7080:7080 --name aionfs-devd aionfs-devd:ci
          for i in {1..10}; do
            sleep 1
            if curl -sf http://127.0.0.1:7080/healthz >/dev/null; then
              docker stop aionfs-devd
              exit 0
            fi
          done
          docker logs aionfs-devd || true
          docker stop aionfs-devd || true
          exit 1

  publish:
    needs: build-smoke
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push multi-arch image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t $IMAGE_NAME:${{ github.event.release.tag_name }} \
            -t $IMAGE_NAME:latest \
            --push .
      - name: Install cosign
        uses: sigstore/cosign-installer@v3
      - name: Sign images (keyless)
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: |
          cosign sign --yes $IMAGE_NAME:${{ github.event.release.tag_name }}
          cosign sign --yes $IMAGE_NAME:latest
